inherit_from:
  - ../common_rubocop_config.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    # This code was taken from the backports gem. We don't want to mess with it.
    - lib/rspec/core/backport_random.rb
  NewCops:
    enable
  SuggestExtensions: false

# This should go down over time.
Layout/LineLength:
  Max: 130
  Exclude:
    - features/**/*
    - spec/**/*

Lint/EmptyClass:
  Exclude:
    - benchmarks/*
    - lib/rspec/core/formatters/protocol.rb
    - lib/rspec/core/notifications.rb
    - spec/rspec/core/world_spec.rb
    - spec/support/fake_libs/rake/tasklib.rb

Lint/IneffectiveAccessModifier:
  Exclude:
    - lib/rspec/core/memoized_helpers.rb # Fixing this file was too much of a diff

Lint/LiteralInInterpolation:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Exclude:
    - lib/rspec/core/example.rb
    - lib/rspec/core/formatters/syntax_highlighter.rb
    - lib/rspec/core/runner.rb

Lint/SuppressedException:
  Exclude:
    - lib/rspec/core/example.rb
    - lib/rspec/core/mocking_adapters/mocha.rb
    - lib/rspec/core/runner.rb
    - lib/rspec/core/test_unit_assertions_adapter.rb

# This should go down over time.
Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  Max: 206
  Exclude:
    - spec/**/*.rb

# This should go down over time.
Metrics/ClassLength:
  Max: 330

# This should go down over time.
Metrics/CyclomaticComplexity:
  Max: 12

# This should go down over time.
Metrics/MethodLength:
  Max: 39
  Exclude:
    # This defines fixtures as methods
    - spec/support/formatter_support.rb

Metrics/ModuleLength:
  Exclude:
    - spec/rspec/core/configuration_spec.rb

Metrics/PerceivedComplexity:
  Max: 15

Style/BarePercentLiterals:
  Enabled: false

# Exclude the default spec_helper to make it easier to uncomment out
# default settings (for both users and the Cucumber suite).
Style/BlockComments:
  Exclude:
    - lib/rspec/core/project_initializer/spec/spec_helper.rb

# Not sure what to do with this rule yet.
Style/ClassAndModuleChildren:
  Exclude:
    - lib/rspec/core/formatters.rb
    - lib/rspec/core/notifications.rb
    - lib/rspec/core/option_parser.rb
    - lib/rspec/core/reporter.rb

Style/RaiseArgs:
  Exclude:
    - lib/rspec/core/configuration.rb
    - lib/rspec/core/hooks.rb
    - lib/rspec/core/option_parser.rb
    - lib/rspec/core/pending.rb
    - spec/rspec/core/formatters/base_text_formatter_spec.rb

Style/RedundantArgument:
  Exclude:
    - lib/rspec/core/notifications.rb

Style/RedundantBegin:
  Exclude:
    - lib/rspec/core/configuration.rb
    - lib/rspec/core/example_group.rb
