Feature: Setting the `strict_docstring` option

  Use the `strict_docstring` option to require the first argument of an example
  or an example group to be a doc string. Examples accept a `String`, example
  groups additionally accept a `Class` or a `Module`.

  Without it, a `Symbol` or a `Hash` passed in the hope of it being treated as
  metadata is silently turned into a doc string instead: `it :slow do` names an
  example "slow" rather than tagging it with `:slow`, so `--tag slow` does not
  find it.

  This option is enabled in the `spec/spec_helper.rb` generated by `rspec --init`.

  Scenario: By default a symbol is turned into a doc string rather than metadata
    Given a file named "spec/widget_spec.rb" with:
      """ruby
      RSpec.describe "Widget" do
        it :slow do
        end
      end
      """
    When I run `rspec --format doc`
    Then it should pass with "1 example, 0 failures"
    And the output should contain "slow"
    When I run `rspec --tag slow`
    Then it should pass with "0 examples, 0 failures"

  Scenario: `strict_docstring` turns the same mistake into an error
    Given a file named ".rspec" with:
      """
      --require spec_helper
      """
    And a file named "spec/spec_helper.rb" with:
      """ruby
      RSpec.configure do |config|
        config.strict_docstring!
      end
      """
    And a file named "spec/widget_spec.rb" with:
      """ruby
      RSpec.describe "Widget" do
        it :slow do
        end
      end
      """
    When I run `rspec`
    Then it should fail with "Examples must be described with a string, got: `:slow`"

  Scenario: A doc string followed by metadata is the way to tag an example
    Given a file named ".rspec" with:
      """
      --require spec_helper
      """
    And a file named "spec/spec_helper.rb" with:
      """ruby
      RSpec.configure do |config|
        config.strict_docstring!
      end
      """
    And a file named "spec/widget_spec.rb" with:
      """ruby
      RSpec.describe "Widget" do
        it "takes a while", :slow do
        end
      end
      """
    When I run `rspec --tag slow`
    Then it should pass with "1 example, 0 failures"

  Scenario: Example groups still accept a class or a module
    Given a file named ".rspec" with:
      """
      --require spec_helper
      """
    And a file named "spec/spec_helper.rb" with:
      """ruby
      class Widget; end
      module Gadget; end

      RSpec.configure do |config|
        config.strict_docstring!
      end
      """
    And a file named "spec/widget_spec.rb" with:
      """ruby
      RSpec.describe Widget do
        it "is described by a class" do
          expect(described_class).to eq(Widget)
        end
      end

      RSpec.describe Gadget do
        it "is described by a module" do
          expect(described_class).to eq(Gadget)
        end
      end
      """
    When I run `rspec`
    Then it should pass with "2 examples, 0 failures"

  Scenario: Example groups reject a hash intended as metadata
    Given a file named ".rspec" with:
      """
      --require spec_helper
      """
    And a file named "spec/spec_helper.rb" with:
      """ruby
      RSpec.configure do |config|
        config.strict_docstring!
      end
      """
    And a file named "spec/widget_spec.rb" with:
      """ruby
      RSpec.describe :type => :model do
        it "is never reached" do
        end
      end
      """
    When I run `rspec`
    Then it should fail with "Example groups must be described with a string, class or module"
