#!/usr/bin/env ruby

# Turn on verbose to make sure we not generating any ruby warning
$VERBOSE = true

# So our "did they run the rspec command?" detection logic thinks
# that we run `rspec`.
$0 = "rspec"

# For the monorepo build the bundle directory is at the top level
$:.unshift File.expand_path '../../../bundle', __FILE__

require 'bundler/setup'
require 'rspec/support/spec/coverage'

# To use simplecov while running rspec-core's test suite, we must
# load simplecov _before_ loading any of rspec-core's files.
# So, this executable exists purely as a wrapper script that
# first loads simplecov, and then loads rspec.
RSpec::Support::Spec::Coverage.setup do
  root File.expand_path("../..", __FILE__)
  minimum_coverage 100
end

load File.expand_path("../../exe/rspec", __FILE__)
