name: RSpec CI

on:
  push:
    branches:
      - 'dev'
      - 'main'
      - '*-maintenance'
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  docs:
    uses: ./.github/workflows/documentation_coverage.yml

  core:
    uses: ./.github/workflows/rspec.yml
    with:
      library: 'rspec-core'
      rspec_version: '~> 3.13.0'

  mocks:
    uses: ./.github/workflows/rspec.yml
    with:
      library: 'rspec-mocks'
      rspec_version: '~> 3.13.0'

  expectations:
    uses: ./.github/workflows/rspec.yml
    with:
      library: 'rspec-expectations'
      rspec_version: '~> 3.13.0'

  support:
    uses: ./.github/workflows/rspec.yml
    with:
      library: 'rspec-support'
      rspec_version: '~> 3.13.0'
